### PR TITLE
broken reference links

### PR DESCRIPTION
**Pull request by PetarAtanasov**
no extended comments needed

### CODE REVIEW

**Comment by lenadoc** [comment]
Hi Petar,

Thank you very much for your input! Your changes have beenn manually migrated and are already in the Academy.

Your further comments and suggestions would be greately appreciated!

Regards,

The Academy Team

**Comment by PetarAtanasov** [comment]
This is disrespectful towards the contributers, not to merge in their work but copy it and not credit the contributer.

**Comment by lenadoc** [comment]
Hello Petar,

Your contribution is very much appreciated.
Our process is built so that we moderate content to see if the feedback needs to be applied somewhere else and as a commercial entity, we cannot allow direct commits to our public documentation.
We have credited you on the tutorial page here: http://academy.spryker.com/enablement/tutorials_and_howtos/introduction_tutorials/t_hello_world.html
We will be happy to receive any further questions, comments or suggestions that you may have.

Regards,
The Academy Team

**Comment by PetarAtanasov** [comment]
Okay, thanks.
I wasn't aware of your policy.

**Pull request closed without merging**
